services:
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    image: ollama/ollama:latest
    networks:
      - cloudflare-net
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    restart: always
    networks:
      - cloudflare-net
    labels:
      - dockflare.enable=true
      - dockflare.hostname=openwebui.huyab.click
      - dockflare.service=http://openwebui:8080
      - dockflare.access.group=admin-team
networks:
  cloudflare-net:
    name: cloudflare-net
    external: true
