services:
  dokploy-redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./dokploy-redis:/data
    networks:
      - dokploy-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 3s
      retries: 5
  dokploy-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: dokploy
      POSTGRES_DB: dokploy
    volumes:
      - ./dokploy-postgres:/var/lib/postgresql/data
    networks:
      - dokploy-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U dokploy
      interval: 5s
      timeout: 5s
      retries: 10
  dokploy:
    image: dokploy/dokploy:latest
    restart: always
    depends_on:
      dokploy-postgres:
        condition: service_healthy
      dokploy-redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://dokploy:dokploy@dokploy-postgres:5432/dokploy
      REDIS_URL: redis://dokploy-redis:6379
    ports:
      - 3003:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dokploy-data:/etc/dokploy
    networks:
      - dokploy-network
  traefik:
    image: traefik:v2.11
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=huy.ntq02@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/etc/dokploy/traefik/dynamic"
      - "--providers.file.watch=true"
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./dokploy-data:/etc/dokploy
    networks:
      - dokploy-network

networks:
  dokploy-network:
    name: dokploy-network
    driver: overlay
    attachable: true
