services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - ./audiobooks:/audiobooks  # Folder for your audiobooks
      - ./metadata:/metadata      # Folder for metadata (bookmarks, etc.)
    restart: unless-stopped
