services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/root
    command: hbbs

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/root
    command: hbbr