name: firecrawl

services:
  playwright-service:
    image: ghcr.io/mendableai/firecrawl/playwright-service:latest
    environment:
      PORT: 3000
    networks:
      - backend
    cpus: 1.0
    mem_limit: 2G
    restart: unless-stopped

  api:
    image: ghcr.io/mendableai/firecrawl/api:latest
    environment:
      REDIS_URL: redis://redis:6379
      PLAYWRIGHT_MICROSERVICE_URL: http://playwright-service:3000/scrape
      USE_DB_AUTHENTICATION: "false"
      PORT: 3002
      HOST: 0.0.0.0
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - playwright-service
    networks:
      - backend
    cpus: 1.0
    mem_limit: 2G
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
