[sources.docker_logs]
type = "docker_logs"
exclude_containers = ["axiom-vector"]

[sinks.axiom]
type = "axiom"
inputs = ["docker_logs"]
token = "${AXIOM_TOKEN}"
dataset = "${AXIOM_DATASET}"
org_id = "${AXIOM_ORG_ID}"
region = "eu-central-1.aws.edge.axiom.co"

[sources.journald_logs]
type = "journald"
journal_directory = "/var/log/journal"
include_units = ["xrdp", "xrdp-sesman"]

[sinks.axiom_journald]
type = "axiom"
inputs = ["journald_logs"]
token = "${AXIOM_TOKEN}"
dataset = "${AXIOM_DATASET}"
org_id = "${AXIOM_ORG_ID}"
region = "eu-central-1.aws.edge.axiom.co"

[sources.host_metrics]
type = "host_metrics"
scrape_interval_secs = 30

[sources.cadvisor]
type = "prometheus_scrape"
endpoints = ["http://cadvisor:8080/metrics"]
scrape_interval_secs = 30

[transforms.metrics_to_log]
type = "metric_to_log"
inputs = ["host_metrics", "cadvisor"]

[sinks.axiom_metrics]
type = "axiom"
inputs = ["metrics_to_log"]
token = "${AXIOM_TOKEN}"
dataset = "${AXIOM_METRICS_DATASET}"
org_id = "${AXIOM_ORG_ID}"
region = "eu-central-1.aws.edge.axiom.co"
